### ISSUE TITLE
how to make GVR run if my project had jni too

### ISSUE THREAD

**Issue by chenwulue** [googlevr/gvr-android-sdk#110]
if I want the GVR woking as usual when the other jni in my project, I will meet the mistakes as followed
`Binary XML file line #40: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView`
My device is Xiaomi MI NOTE PRO

**Comment by sigmaxipi** [comment]
What is the full stacktrace? Is it failing to load an .so file? If so, the error might be due to using a mix of 64-bit and 32-bit native libraries. You should build a 32-bit version of your native code or see [libraries/native/README.md](https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native) for details on how to use 64-bit versions of GVR.

**Comment by sigmaxipi** [comment]
This is fixed now that the .aars include multiple architectures.

**Comment by dri94** [comment]
This error is still present on the galaxy s7. `android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView`

**Comment by trusttri** [comment]
Mine is galaxy s6, and I am having the same issue.
