### ISSUE TITLE
At least from v1.20.0-1-g0c1b111 no app modules are run when importing to Android Studio.

### ISSUE THREAD

**Issue by Cristo86** [googlevr/gvr-android-sdk#389]
There is needed to do some manual work to make it work on Android Studio. Maybe some instructions would be added or a known minimal version.*

Also https://developers.google.com/vr/android/ndk/get-started should be updated as the instruction for controllerpaint still refers to old paths/ways ( ndk/demos/controllerpaint ) to build.

\* Error happening when trying to build Plugin with id 'com.android.model.application' not found

**Comment by Cristo86** [comment]
In Version 1.40.0 (maybe before it was too, haven't tried) settings.gradle explains the reason of those ndk disabled modules:

```
// NDK samples are disabled by default because they need the Android NDK to be
// installed in addition to the SDK. To build them, first extract the NDK .so
// files by running "./gradlew :extractNdk" which will create a libraries/jni
// folder. Then uncomment these lines to enable the NDK samples and synchronize
// Android Studio.
```

It seems also that the get started page was corrected.

**Comment by alculquicondor** [comment]
I'm still getting `Plugin with id 'com.android.model.application' not found.`, even when running `./gradlew :extractNdk`. What should I do?
