### ISSUE TITLE
Double vision on Samsung S7 (N+) using VrVideoView 

### ISSUE THREAD

**Issue by njudit8** [googlevr/gvr-android-sdk#500]
We are also experiencing the double vision issue described in:
[https://github.com/googlevr/gvr-unity-sdk/issues/421](https://github.com/googlevr/gvr-unity-sdk/issues/421)

We are using the VrVideoView from the Android SDK to display a VR video (3dh) with Cardboard. The issue only occurs on Samsung S7 (Android 7.0). 

On S7, the complete 360 video is made up of only 2 views in stereo view (compared to several other devices including Samsung S6(N+), where it consists of 4 views, and there is no distortion). The video is stretched and there is a significant mismatch between left and right views, as you can see in the screenshot below. As a result, there is double-vision when viewed in Cardboard.

Changing the resolution did not solve the problem.

Thanks for looking into this.
![double_vision_s7](https://user-images.githubusercontent.com/25366812/33315441-68179080-d439-11e7-9196-0f34ddadf624.png)

**Comment by jdduke** [comment]
HI @njudit8, can you include which version of the SDK you're using, and which version of Google VR Services (if any) you have installed? Thanks.

**Comment by njudit8** [comment]
Hi @jdduke, 
Google VR Services version `1.10.172754103`
Google VR SDK  `v1.101.0`
Thanks.

**Comment by njudit8** [comment]
Updating to the latest version of Google VR Services has still not resolved the issue.
Any suggestions?

**Comment by Carlos-CR** [comment]
Not sure if it is the same issue, but from the screenshots it looks so. I recently had similar issues happening only on S7 and S8 devices. The solution, as it turned out, had to do with a setting in Samsung devices, under Settings > Screen > Screen Resolution. Having anything other than the max resolution caused the issue.

Dropping this just in case anyone else also had this issue.

**Comment by jdduke** [comment]
@njudit8: Are you seeing the same problem with the SimpleVideoWidget sample provided by the SDK? Have you updated your SDK to the latest 1.20.0 release? The VR Views (pano/video widgets) wouldn't necessarily be fixed by a VrCore upgrade.

**Comment by njudit8** [comment]
@Carlos-CR Thanks! For some reason, changing the resolution to WQHD solved the issue. 

@jdduke  Although the bug does not appear on WQHD anymore, it is still present on lower resolutions. This is highly problematic on S7, due to another bug (switching to a lower resolution, even WQHD is shown as the set resolution).
Yes, same problem with the SDK sample, and updating to the latest release did not help.

**Comment by jdduke** [comment]
Hi @njudit8. We landed a fix in the 1.30 SDK release. Pleas give that a try, and re-open if it's still unresolved. Thanks for your patience.
